[package]
description = "Regular expression set parser at run time"
edition = "2021"
license-file = "LICENSE"
name = "re-set"
version = "0.0.1-alpha.0"

[workspace]
members = ["macros"]

[dependencies]
regex = "1.7.1"
regex-syntax = "0.6.28"
